services:
  - type: web
    name: seoultech-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production





  - type: web
    name: seoultech-frontend
    env: static  # This makes it a static site under the hood
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: VITE_API_URL
        value: https://seoultech-backend.onrender.com/
#render.yaml test
